services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -U app_user"]
      interval: 2s
      timeout: 5s
      retries: 15
    ports:
      - "5432:5432"

  fastzero_app:
    image: fastzero_app
    build: .
    ports:
      - "7000:7000"
    depends_on:
      - database
    restart: always
    environment:
      DATABASE_URL: "postgresql+psycopg://app_user:app_password@database:5432/app_db"

volumes:
  pgdata: